name: Deploy React App to VPS

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up SSH
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Step 3: Install Node.js and dependencies
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # Step 4: Build the React app
      - name: Build React app
        run: npm run build

      # Step 5: Deploy to VPS
      - name: Deploy to VPS
        run: |
          # Add server to known hosts
          mkdir -p ~/.ssh
          ssh-keyscan -H 203.82.193.150 >> ~/.ssh/known_hosts

          # Create deployment script
          cat > deploy.sh << 'EOF'
          #!/bin/bash
          cd /var/www/linkedgage
          git pull
          npm ci
          npm run build
          sudo systemctl restart nginx
          EOF

          # Upload deployment script
          scp -o StrictHostKeyChecking=no deploy.sh utsho@203.82.193.150:/tmp/

          # Execute deployment script
          ssh -o StrictHostKeyChecking=no utsho@203.82.193.150 "chmod +x /tmp/deploy.sh && sudo /tmp/deploy.sh"

      # Step 6: Verify deployment
      - name: Verify deployment
        run: |
          curl -f https://linkedgage.com || exit 1
