name: Deploy React App to VPS

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # This runs on the latest Ubuntu runner

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up SSH for secure communication with the server
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # Use the private key stored in GitHub secrets

      # Step 3: Install Node.js and dependencies
      - name: Set up Node.js and install dependencies
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: npm install

      # Step 4: Build the React app
      - name: Build React app
        run: npm run build

      # Step 5: Deploy to the VPS server
      - name: Deploy to VPS server
        run: |
          # Remove the old build folder on the server (important!)
          ssh -o StrictHostKeyChecking=no utsho@203.82.193.150 "rm -rf /home/utsho1/htdocs/linkedgage/build"

          # Upload the entire build folder (not just contents)
          scp -o StrictHostKeyChecking=no -r ./build utsho@203.82.193.150:/home/utsho1/htdocs/linkedgage/

          # Restart Nginx to apply changes
          ssh -o StrictHostKeyChecking=no utsho@203.82.193.150 << 'EOF'
            sudo systemctl restart nginx || exit 1
          EOF
